import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navLinkRs = [
  { id: 1, name: 'Home', path: '/' },
  { id: 2, name: 'About', path: '/About' },
  { id: 3, name: 'Contact', path: 'Contact' },
  { id: 4, name: 'Shop', path: '/Shop' },
  { id: 5, name: 'Menu', path: '/Menu' },
];

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-3">
        <nav>
          <ul className="flex items-center gap-4 pb-10">
            {navLinkRs.map(item => (
              <li key={item.id}>
                <Link className="font-medium text-lg" href={item.path}>
                  {item.name}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
